// Generated by `npm run generate-stats` from `Bybit-UTA-AllPerp-ClosedPosition-1774220400-1790114399.csv`.
// Do not edit by hand: drop the new export in `src/Data/`, then run the script again.

// `pnl` is the net result of that week or day alone, `cumulativePnl` the running total since
// the start of the window. Both in whole dollars
export type PnlPoint = {
  date: string;
  label: string;
  pnl: number;
  cumulativePnl: number;
}

// The net result of one trading pair over the whole window, in whole dollars. Each list below
// holds the 10 largest by absolute value, ordered from the biggest profit to the biggest loss
export type PairPnl = {
  pair: string;
  pnl: number;
}

// The last day covered by the source export
export const statsAsOf = "2026-09-22"

export const vol6months = 68064838

export const pnlStats6months: PnlPoint[] = [
  { date: "2026-03-23", label: "23-29 mar", pnl: 779, cumulativePnl: 779 },
  { date: "2026-03-30", label: "30 mar - 5 apr", pnl: -35, cumulativePnl: 745 },
  { date: "2026-04-06", label: "6-12 apr", pnl: -50, cumulativePnl: 695 },
  { date: "2026-04-13", label: "13-19 apr", pnl: -947, cumulativePnl: -252 },
  { date: "2026-04-20", label: "20-26 apr", pnl: 484, cumulativePnl: 232 },
  { date: "2026-04-27", label: "27 apr - 3 may", pnl: 1, cumulativePnl: 233 },
  { date: "2026-05-04", label: "4-10 may", pnl: 198, cumulativePnl: 431 },
  { date: "2026-05-11", label: "11-17 may", pnl: 70, cumulativePnl: 501 },
  { date: "2026-05-18", label: "18-24 may", pnl: 2097, cumulativePnl: 2598 },
  { date: "2026-05-25", label: "25-31 may", pnl: 445, cumulativePnl: 3044 },
  { date: "2026-06-01", label: "1-7 jun", pnl: 5475, cumulativePnl: 8519 },
  { date: "2026-06-08", label: "8-14 jun", pnl: 2219, cumulativePnl: 10737 },
  { date: "2026-06-15", label: "15-21 jun", pnl: 3139, cumulativePnl: 13876 },
  { date: "2026-06-22", label: "22-28 jun", pnl: -1180, cumulativePnl: 12696 },
  { date: "2026-06-29", label: "29 jun - 5 jul", pnl: 1821, cumulativePnl: 14517 },
  { date: "2026-07-06", label: "6-12 jul", pnl: -3446, cumulativePnl: 11071 },
  { date: "2026-07-13", label: "13-19 jul", pnl: -884, cumulativePnl: 10187 },
  { date: "2026-07-20", label: "20-26 jul", pnl: 1407, cumulativePnl: 11594 },
  { date: "2026-07-27", label: "27 jul - 2 aug", pnl: 1377, cumulativePnl: 12971 },
  { date: "2026-08-03", label: "3-9 aug", pnl: 2047, cumulativePnl: 15018 },
  { date: "2026-08-10", label: "10-16 aug", pnl: 2103, cumulativePnl: 17121 },
  { date: "2026-08-17", label: "17-23 aug", pnl: -778, cumulativePnl: 16343 },
  { date: "2026-08-24", label: "24-30 aug", pnl: 7362, cumulativePnl: 23705 },
  { date: "2026-08-31", label: "31 aug - 6 sep", pnl: -890, cumulativePnl: 22814 },
  { date: "2026-09-07", label: "7-13 sep", pnl: 1580, cumulativePnl: 24394 },
  { date: "2026-09-14", label: "14-20 sep", pnl: 754, cumulativePnl: 25148 },
  { date: "2026-09-21", label: "21-22 sep", pnl: 4634, cumulativePnl: 29782 }
]

export const pnlPerPair6months: PairPnl[] = [
  { pair: "HYPEUSDT", pnl: 14054 },
  { pair: "TAOUSDT", pnl: 9704 },
  { pair: "NEARUSDT", pnl: 7395 },
  { pair: "WLDUSDT", pnl: 2536 },
  { pair: "PUMPFUNUSDT", pnl: 1862 },
  { pair: "LITUSDT", pnl: 1532 },
  { pair: "MONUSDT", pnl: 707 },
  { pair: "TONUSDT", pnl: -529 },
  { pair: "EDGEUSDT", pnl: -558 },
  { pair: "XLMUSDT", pnl: -6496 }
]

export const vol30days = 16446843

export const pnlStats30days: PnlPoint[] = [
  { date: "2026-08-24", label: "24 aug", pnl: 3321, cumulativePnl: 3321 },
  { date: "2026-08-25", label: "25 aug", pnl: -319, cumulativePnl: 3002 },
  { date: "2026-08-26", label: "26 aug", pnl: 1464, cumulativePnl: 4466 },
  { date: "2026-08-27", label: "27 aug", pnl: 1470, cumulativePnl: 5937 },
  { date: "2026-08-28", label: "28 aug", pnl: 1392, cumulativePnl: 7329 },
  { date: "2026-08-29", label: "29 aug", pnl: 623, cumulativePnl: 7952 },
  { date: "2026-08-30", label: "30 aug", pnl: -590, cumulativePnl: 7362 },
  { date: "2026-08-31", label: "31 aug", pnl: -1188, cumulativePnl: 6173 },
  { date: "2026-09-01", label: "1 sep", pnl: 383, cumulativePnl: 6556 },
  { date: "2026-09-02", label: "2 sep", pnl: 389, cumulativePnl: 6945 },
  { date: "2026-09-03", label: "3 sep", pnl: 51, cumulativePnl: 6996 },
  { date: "2026-09-04", label: "4 sep", pnl: -667, cumulativePnl: 6329 },
  { date: "2026-09-05", label: "5 sep", pnl: 162, cumulativePnl: 6491 },
  { date: "2026-09-06", label: "6 sep", pnl: -19, cumulativePnl: 6471 },
  { date: "2026-09-07", label: "7 sep", pnl: 534, cumulativePnl: 7005 },
  { date: "2026-09-08", label: "8 sep", pnl: -88, cumulativePnl: 6917 },
  { date: "2026-09-09", label: "9 sep", pnl: -577, cumulativePnl: 6340 },
  { date: "2026-09-10", label: "10 sep", pnl: 1342, cumulativePnl: 7682 },
  { date: "2026-09-11", label: "11 sep", pnl: -254, cumulativePnl: 7427 },
  { date: "2026-09-12", label: "12 sep", pnl: 0, cumulativePnl: 7427 },
  { date: "2026-09-13", label: "13 sep", pnl: 624, cumulativePnl: 8051 },
  { date: "2026-09-14", label: "14 sep", pnl: 272, cumulativePnl: 8323 },
  { date: "2026-09-15", label: "15 sep", pnl: -3620, cumulativePnl: 4703 },
  { date: "2026-09-16", label: "16 sep", pnl: 283, cumulativePnl: 4986 },
  { date: "2026-09-17", label: "17 sep", pnl: 79, cumulativePnl: 5065 },
  { date: "2026-09-18", label: "18 sep", pnl: 1775, cumulativePnl: 6840 },
  { date: "2026-09-19", label: "19 sep", pnl: 1839, cumulativePnl: 8679 },
  { date: "2026-09-20", label: "20 sep", pnl: 126, cumulativePnl: 8805 },
  { date: "2026-09-21", label: "21 sep", pnl: 3663, cumulativePnl: 12468 },
  { date: "2026-09-22", label: "22 sep", pnl: 971, cumulativePnl: 13439 }
]

export const pnlPerPair30days: PairPnl[] = [
  { pair: "NEARUSDT", pnl: 7492 },
  { pair: "TAOUSDT", pnl: 7100 },
  { pair: "WLDUSDT", pnl: 2191 },
  { pair: "HYPEUSDT", pnl: 1403 },
  { pair: "PUMPFUNUSDT", pnl: 648 },
  { pair: "LSKUSDT", pnl: -198 },
  { pair: "PENGUUSDT", pnl: -250 },
  { pair: "ONDOUSDT", pnl: -354 },
  { pair: "XLMUSDT", pnl: -2439 },
  { pair: "LITUSDT", pnl: -2819 }
]
