// Generated by `npm run generate-stats` from `Bybit-UTA-AllPerp-ClosedPosition-1774479600-1790373599.csv`.
// Do not edit by hand: drop the new export in `src/Data/`, then run the script again.

// `pnl` is the net result of that week or day alone, `cumulativePnl` the running total since
// the start of the window. Both in whole dollars
export type PnlPoint = {
  date: string;
  label: string;
  pnl: number;
  cumulativePnl: number;
}

// The net result of one trading pair over the whole window, in whole dollars. Each list below
// holds the 10 largest by absolute value, ordered from the biggest profit to the biggest loss
export type PairPnl = {
  pair: string;
  pnl: number;
}

// The last day covered by the source export
export const statsAsOf = "2026-09-25"

export const vol6months = 71933170

export const pnlStats6months: PnlPoint[] = [
  { date: "2026-03-26", label: "26-29 mar", pnl: 635, cumulativePnl: 635 },
  { date: "2026-03-30", label: "30 mar - 5 apr", pnl: -35, cumulativePnl: 600 },
  { date: "2026-04-06", label: "6-12 apr", pnl: -50, cumulativePnl: 550 },
  { date: "2026-04-13", label: "13-19 apr", pnl: -947, cumulativePnl: -397 },
  { date: "2026-04-20", label: "20-26 apr", pnl: 484, cumulativePnl: 87 },
  { date: "2026-04-27", label: "27 apr - 3 may", pnl: 1, cumulativePnl: 88 },
  { date: "2026-05-04", label: "4-10 may", pnl: 198, cumulativePnl: 287 },
  { date: "2026-05-11", label: "11-17 may", pnl: 70, cumulativePnl: 356 },
  { date: "2026-05-18", label: "18-24 may", pnl: 2097, cumulativePnl: 2454 },
  { date: "2026-05-25", label: "25-31 may", pnl: 445, cumulativePnl: 2899 },
  { date: "2026-06-01", label: "1-7 jun", pnl: 5475, cumulativePnl: 8374 },
  { date: "2026-06-08", label: "8-14 jun", pnl: 2219, cumulativePnl: 10592 },
  { date: "2026-06-15", label: "15-21 jun", pnl: 3139, cumulativePnl: 13731 },
  { date: "2026-06-22", label: "22-28 jun", pnl: -1180, cumulativePnl: 12551 },
  { date: "2026-06-29", label: "29 jun - 5 jul", pnl: 1821, cumulativePnl: 14372 },
  { date: "2026-07-06", label: "6-12 jul", pnl: -3446, cumulativePnl: 10926 },
  { date: "2026-07-13", label: "13-19 jul", pnl: -884, cumulativePnl: 10042 },
  { date: "2026-07-20", label: "20-26 jul", pnl: 1407, cumulativePnl: 11449 },
  { date: "2026-07-27", label: "27 jul - 2 aug", pnl: 1377, cumulativePnl: 12826 },
  { date: "2026-08-03", label: "3-9 aug", pnl: 2047, cumulativePnl: 14873 },
  { date: "2026-08-10", label: "10-16 aug", pnl: 2103, cumulativePnl: 16976 },
  { date: "2026-08-17", label: "17-23 aug", pnl: -778, cumulativePnl: 16198 },
  { date: "2026-08-24", label: "24-30 aug", pnl: 7362, cumulativePnl: 23560 },
  { date: "2026-08-31", label: "31 aug - 6 sep", pnl: -890, cumulativePnl: 22670 },
  { date: "2026-09-07", label: "7-13 sep", pnl: 1580, cumulativePnl: 24250 },
  { date: "2026-09-14", label: "14-20 sep", pnl: 754, cumulativePnl: 25004 },
  { date: "2026-09-21", label: "21-25 sep", pnl: 9742, cumulativePnl: 34745 }
]

export const pnlPerPair6months: PairPnl[] = [
  { pair: "HYPEUSDT", pnl: 13909 },
  { pair: "TAOUSDT", pnl: 12473 },
  { pair: "NEARUSDT", pnl: 9443 },
  { pair: "PUMPFUNUSDT", pnl: 2227 },
  { pair: "XPLUSDT", pnl: 939 },
  { pair: "WLDUSDT", pnl: 859 },
  { pair: "ZROUSDT", pnl: 745 },
  { pair: "MONUSDT", pnl: 707 },
  { pair: "EDGEUSDT", pnl: -558 },
  { pair: "XLMUSDT", pnl: -6496 }
]

export const vol30days = 17587483

export const pnlStats30days: PnlPoint[] = [
  { date: "2026-08-27", label: "27 aug", pnl: 1470, cumulativePnl: 1470 },
  { date: "2026-08-28", label: "28 aug", pnl: 1392, cumulativePnl: 2862 },
  { date: "2026-08-29", label: "29 aug", pnl: 623, cumulativePnl: 3486 },
  { date: "2026-08-30", label: "30 aug", pnl: -590, cumulativePnl: 2895 },
  { date: "2026-08-31", label: "31 aug", pnl: -1188, cumulativePnl: 1707 },
  { date: "2026-09-01", label: "1 sep", pnl: 383, cumulativePnl: 2090 },
  { date: "2026-09-02", label: "2 sep", pnl: 389, cumulativePnl: 2479 },
  { date: "2026-09-03", label: "3 sep", pnl: 51, cumulativePnl: 2530 },
  { date: "2026-09-04", label: "4 sep", pnl: -667, cumulativePnl: 1863 },
  { date: "2026-09-05", label: "5 sep", pnl: 162, cumulativePnl: 2024 },
  { date: "2026-09-06", label: "6 sep", pnl: -19, cumulativePnl: 2005 },
  { date: "2026-09-07", label: "7 sep", pnl: 534, cumulativePnl: 2539 },
  { date: "2026-09-08", label: "8 sep", pnl: -88, cumulativePnl: 2451 },
  { date: "2026-09-09", label: "9 sep", pnl: -577, cumulativePnl: 1874 },
  { date: "2026-09-10", label: "10 sep", pnl: 1342, cumulativePnl: 3216 },
  { date: "2026-09-11", label: "11 sep", pnl: -254, cumulativePnl: 2961 },
  { date: "2026-09-12", label: "12 sep", pnl: 0, cumulativePnl: 2961 },
  { date: "2026-09-13", label: "13 sep", pnl: 624, cumulativePnl: 3585 },
  { date: "2026-09-14", label: "14 sep", pnl: 272, cumulativePnl: 3857 },
  { date: "2026-09-15", label: "15 sep", pnl: -3620, cumulativePnl: 237 },
  { date: "2026-09-16", label: "16 sep", pnl: 283, cumulativePnl: 520 },
  { date: "2026-09-17", label: "17 sep", pnl: 79, cumulativePnl: 599 },
  { date: "2026-09-18", label: "18 sep", pnl: 1775, cumulativePnl: 2374 },
  { date: "2026-09-19", label: "19 sep", pnl: 1839, cumulativePnl: 4213 },
  { date: "2026-09-20", label: "20 sep", pnl: 126, cumulativePnl: 4339 },
  { date: "2026-09-21", label: "21 sep", pnl: 3663, cumulativePnl: 8002 },
  { date: "2026-09-22", label: "22 sep", pnl: 2351, cumulativePnl: 10353 },
  { date: "2026-09-23", label: "23 sep", pnl: 1540, cumulativePnl: 11893 },
  { date: "2026-09-24", label: "24 sep", pnl: 192, cumulativePnl: 12085 },
  { date: "2026-09-25", label: "25 sep", pnl: 1996, cumulativePnl: 14081 }
]

export const pnlPerPair30days: PairPnl[] = [
  { pair: "NEARUSDT", pnl: 9131 },
  { pair: "TAOUSDT", pnl: 6960 },
  { pair: "HYPEUSDT", pnl: 1043 },
  { pair: "XPLUSDT", pnl: 939 },
  { pair: "PUMPFUNUSDT", pnl: 932 },
  { pair: "ZROUSDT", pnl: 745 },
  { pair: "ONDOUSDT", pnl: 358 },
  { pair: "ENAUSDT", pnl: -228 },
  { pair: "XLMUSDT", pnl: -2599 },
  { pair: "LITUSDT", pnl: -3714 }
]
