// Generated by `npm run generate-stats` from `Bybit-UTA-AllPerp-ClosedPosition-1772406000-1788299999.csv`.
// Do not edit by hand: drop the new export in `src/Data/`, then run the script again.

// `pnl` is the net result of that week or day alone, `cumulativePnl` the running total since
// the start of the window. Both in whole dollars
export type PnlPoint = {
  date: string;
  label: string;
  pnl: number;
  cumulativePnl: number;
}

// The last day covered by the source export
export const statsAsOf = "2026-08-31"

export const vol6months = 56820739

export const pnlStats6months: PnlPoint[] = [
  { date: "2026-03-02", label: "2-8 mar", pnl: -1, cumulativePnl: -1 },
  { date: "2026-03-09", label: "9-15 mar", pnl: -3, cumulativePnl: -4 },
  { date: "2026-03-16", label: "16-22 mar", pnl: 68, cumulativePnl: 64 },
  { date: "2026-03-23", label: "23-29 mar", pnl: 779, cumulativePnl: 844 },
  { date: "2026-03-30", label: "30 mar - 5 apr", pnl: -35, cumulativePnl: 809 },
  { date: "2026-04-06", label: "6-12 apr", pnl: -50, cumulativePnl: 759 },
  { date: "2026-04-13", label: "13-19 apr", pnl: -947, cumulativePnl: -188 },
  { date: "2026-04-20", label: "20-26 apr", pnl: 484, cumulativePnl: 297 },
  { date: "2026-04-27", label: "27 apr - 3 may", pnl: 1, cumulativePnl: 298 },
  { date: "2026-05-04", label: "4-10 may", pnl: 198, cumulativePnl: 496 },
  { date: "2026-05-11", label: "11-17 may", pnl: 70, cumulativePnl: 565 },
  { date: "2026-05-18", label: "18-24 may", pnl: 2097, cumulativePnl: 2663 },
  { date: "2026-05-25", label: "25-31 may", pnl: 445, cumulativePnl: 3108 },
  { date: "2026-06-01", label: "1-7 jun", pnl: 5475, cumulativePnl: 8583 },
  { date: "2026-06-08", label: "8-14 jun", pnl: 2219, cumulativePnl: 10802 },
  { date: "2026-06-15", label: "15-21 jun", pnl: 3139, cumulativePnl: 13941 },
  { date: "2026-06-22", label: "22-28 jun", pnl: -1180, cumulativePnl: 12761 },
  { date: "2026-06-29", label: "29 jun - 5 jul", pnl: 1821, cumulativePnl: 14581 },
  { date: "2026-07-06", label: "6-12 jul", pnl: -3446, cumulativePnl: 11135 },
  { date: "2026-07-13", label: "13-19 jul", pnl: -884, cumulativePnl: 10252 },
  { date: "2026-07-20", label: "20-26 jul", pnl: 1407, cumulativePnl: 11658 },
  { date: "2026-07-27", label: "27 jul - 2 aug", pnl: 1377, cumulativePnl: 13035 },
  { date: "2026-08-03", label: "3-9 aug", pnl: 2047, cumulativePnl: 15082 },
  { date: "2026-08-10", label: "10-16 aug", pnl: 2103, cumulativePnl: 17185 },
  { date: "2026-08-17", label: "17-23 aug", pnl: -778, cumulativePnl: 16408 },
  { date: "2026-08-24", label: "24-30 aug", pnl: 7362, cumulativePnl: 23769 },
  { date: "2026-08-31", label: "31 aug", pnl: -1188, cumulativePnl: 22581 }
]

export const vol30days = 12676263

export const pnlStats30days: PnlPoint[] = [
  { date: "2026-08-02", label: "2 aug", pnl: 127, cumulativePnl: 127 },
  { date: "2026-08-03", label: "3 aug", pnl: 57, cumulativePnl: 184 },
  { date: "2026-08-04", label: "4 aug", pnl: 209, cumulativePnl: 393 },
  { date: "2026-08-05", label: "5 aug", pnl: 370, cumulativePnl: 764 },
  { date: "2026-08-06", label: "6 aug", pnl: 408, cumulativePnl: 1172 },
  { date: "2026-08-07", label: "7 aug", pnl: 667, cumulativePnl: 1839 },
  { date: "2026-08-08", label: "8 aug", pnl: 80, cumulativePnl: 1919 },
  { date: "2026-08-09", label: "9 aug", pnl: 255, cumulativePnl: 2174 },
  { date: "2026-08-10", label: "10 aug", pnl: 990, cumulativePnl: 3164 },
  { date: "2026-08-11", label: "11 aug", pnl: -51, cumulativePnl: 3113 },
  { date: "2026-08-12", label: "12 aug", pnl: 110, cumulativePnl: 3224 },
  { date: "2026-08-13", label: "13 aug", pnl: 360, cumulativePnl: 3584 },
  { date: "2026-08-14", label: "14 aug", pnl: 50, cumulativePnl: 3634 },
  { date: "2026-08-15", label: "15 aug", pnl: 243, cumulativePnl: 3876 },
  { date: "2026-08-16", label: "16 aug", pnl: 401, cumulativePnl: 4277 },
  { date: "2026-08-17", label: "17 aug", pnl: 17, cumulativePnl: 4294 },
  { date: "2026-08-18", label: "18 aug", pnl: -1058, cumulativePnl: 3236 },
  { date: "2026-08-19", label: "19 aug", pnl: 485, cumulativePnl: 3721 },
  { date: "2026-08-20", label: "20 aug", pnl: 150, cumulativePnl: 3871 },
  { date: "2026-08-21", label: "21 aug", pnl: 2138, cumulativePnl: 6009 },
  { date: "2026-08-22", label: "22 aug", pnl: -4755, cumulativePnl: 1253 },
  { date: "2026-08-23", label: "23 aug", pnl: 2247, cumulativePnl: 3500 },
  { date: "2026-08-24", label: "24 aug", pnl: 3321, cumulativePnl: 6821 },
  { date: "2026-08-25", label: "25 aug", pnl: -319, cumulativePnl: 6502 },
  { date: "2026-08-26", label: "26 aug", pnl: 1464, cumulativePnl: 7966 },
  { date: "2026-08-27", label: "27 aug", pnl: 1470, cumulativePnl: 9436 },
  { date: "2026-08-28", label: "28 aug", pnl: 1392, cumulativePnl: 10828 },
  { date: "2026-08-29", label: "29 aug", pnl: 623, cumulativePnl: 11452 },
  { date: "2026-08-30", label: "30 aug", pnl: -590, cumulativePnl: 10861 },
  { date: "2026-08-31", label: "31 aug", pnl: -1188, cumulativePnl: 9673 }
]
